Ajustes poc
douglassouza07/poc-kotlin pull request #1
Opened 2022-03-10 03:28 UTC by douglassouza07

Segue correções conforme solicitada por e-mail.

O projeto ja esta enviando e consumindo as mensagem do kafka.

2022-03-11 12:46 UTC, guilhermelodi commented on build.gradle.kts
> +    implementation("org.projectlombok:lombok:1.18.20")
Por que você precisou do lombok?

2022-03-11 12:49 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/config/UserProducerConfig.kt
> +        return KafkaTemplate<String, String>(producerFactory())
Não precisa definir os valores do generics nessa linha.

2022-03-11 12:49 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/config/UserProducerConfig.kt
> +        return DefaultKafkaProducerFactory<String, String>(producerConfigs())
Não precisa definir os valores do generics nessa linha.

2022-03-11 12:53 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/dto/UserDto.kt
> +    @get:NotEmpty(message = "O documento é obrigatorio")
Douglas, na outra versão você utilizou `@field:` e nessa está utilizando `@get`. Por que geralmente você utiliza esses operadores?

2022-03-11 12:54 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/exception/ExceptionHandler.kt
> +import org.springframework.http.converter.HttpMessageNotReadableException
import não utilizado

2022-03-11 12:57 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/kafka/UserConsumer.kt
> +    fun processMessage(playload: String) {
Aqui existe alguma forma de receber direto o tipo da mensagem? Nesse caso, `User`?

2022-03-11 12:58 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/kafka/UserConsumer.kt
> +        log.info("Consumindo dados {}")
Aqui o log está estranho

2022-03-11 12:58 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/kafka/UserConsumer.kt
> +        log.info("User atualizado com sucesso {}")
Aqui também.

2022-03-11 13:33 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/config/UserProducerConfig.kt
> +class UserProducerConfig {
Douglas, vi que você criou uma configuração direto no código. Tem alguma diferença utilizando Spring Boot? Eu gostaria que você pesquisasse sobre essa integração Spring Kafka + Spring Boot.

2022-03-11 13:33 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/config/UserProducerConfig.kt
> +class UserProducerConfig {
(a mesma coisa com relação ao ConsumerConfig)

2022-03-11 13:38 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/util/ValidateDocument.kt
> +    fun cpfCnpj(user: User): User {
Achei estranho esse método. Ele valida o cpfCnpj e retorna um Usuário?

2022-03-11 13:39 UTC, guilhermelodi requested changes
Assim que finalizar os comentários, me avise por favor.

2022-03-18 12:59 UTC, douglassouza07 commented on build.gradle.kts
> +    implementation("org.projectlombok:lombok:1.18.20")
Foi retirado não estou usando.

2022-03-18 13:18 UTC, douglassouza07 commented on src/main/kotlin/br/com/poc/dto/UserDto.kt
> +    @get:NotEmpty(message = "O documento é obrigatorio")
No Kotlin conseguimos acessar uma property, e não diretamente os atributos da classe então embora o Target da annotaion suporte a utilização em um field, precisamos indicar para o Kotlin nesse caso posso utlizar tantto o @get ou @field foi isso que entendi quando estava pesquisando.

2022-03-18 13:35 UTC, douglassouza07 commented on src/main/kotlin/br/com/poc/util/ValidateDocument.kt
> +    fun cpfCnpj(user: User): User {
SIm Lodi ficou estranho mesmo deixei a validação agora em um unico metodo, e deixei a classe ValidateDocument como um auxiliar apenas para validar o documento.

2022-03-22 20:45 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/dto/UserDto.kt
> +    @get:NotEmpty(message = "O documento é obrigatorio")
Buscando ser mais conciso, depois faça um teste sem o `@get:`

2022-03-22 20:48 UTC, guilhermelodi commented on src/main/kotlin/br/com/poc/kafka/UserConsumer.kt
> +        log.info("User atualizado com sucesso {}")
Você colocou esse comentário como resolvido, mas acho que não foi.

2022-03-23 01:22 UTC, guilhermelodi commented
Ajustando os últimos comentários, está aprovado

2022-03-23 01:23 UTC, guilhermelodi approved these changes

2022-03-23 02:30 UTC, merged